### ISSUE TITLE
[OLD] Legacy Polish Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/pl.react.dev#1]
## Slack
**https://react-translations.slack.com - join to see the glossary and chat with other team members!**
Channels:
**\#pl** - general discussion
**\#pl-glossary** - the glossary (use the search feature to find words)

## Maintainer List

* @jakubdrozdek

### Retired maintainers

* @TeoTN
* @cvqprs
* @marcinostrouch
* @iamarek
* @arekmaz
* @g12i
* @bartlomiejzuber

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For Maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #1

When PRs are merged, make sure to mark that page as completed!
**Note:** We require two maintainers to approve a PR for it to be merged.

**Note:** Since most of the PRs are created from forks, we can't add our own commits to them. Let's make a rule that **if a PR's author doesn't respond within 7 days, we take the translated page over.** Another person can create their own PR with the translated content, apply any suggestions added to the old PR, and submit. To be fair, let's not remove entirely the original author from the list below - just add the new translator after comma.
If the author leaves a message that they won't be available for a few days - that's fine, we'll wait.

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@jakubdrozdek) #27 
* [x] Tutorial (@jakubdrozdek) #12

### Basics

* [x] Hello World (@cvqprs @TeoTN) #38  
* [x] Introducing JSX (@cvqprs @TeoTN) #39 
* [x] Rendering Elements (@arekmaz) #42 
* [x] Components and Props (@arekmaz) #45 
* [x] State and Lifecycle (@jakubdrozdek) #8 
* [x] Handling Events (@jakubdrozdek) #5 
* [x] Conditional Rendering (@marcinostrouch) #59 
* [x] Lists and Keys (@bartlomiejzuber) #58 
* [x] Forms (@marcinostrouch ) #57 
* [x] Lifting State Up (@iamarek) #11 
* [x] Composition vs Inheritance (@jakubdrozdek) #10 
* [x] Thinking in React (@marcinostrouch) #15 

### API Reference

* [x] React ( @cvqprs @iamarek) #48 
* [x] React.Component (@arekmaz) #71 
* [x] ReactDOM (@patpienkowski) #35 
* [x] ReactDOMServer (@g12i) #81
* [x] DOM Elements (@cvqprs @czechowiczmateusz) #62  
* [x] SyntheticEvent (@jakubdrozdek) #51
* [x] Test Utilities (@jakubdrozdek) #21 
* [x] Shallow Renderer (@jakubdrozdek) #24 
* [x] Test Renderer (@jakubdrozdek) #25
* [x] JS Environment Requirements (@cvqprs) #34
* [x] Glossary (@jakubdrozdek) #76 

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [x] tutorial/nav.yml (@jakubdrozdek) #56
* [x] docs/nav.yml (@cvqprs) #77

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [x] Getting Started (@iamarek) #6 
* [x] Add React to a Website (@cvqprs) #17 
* [x] Create a New React App (@marcinostrouch) #23 
* [x] CDN Links (@cvqprs) #18  

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@g12i) #28 
  * [x] Hooks at a Glance (@g12i) #33 
  * [x] Using the State Hook (@g12i) #40 
  * [x] Using the Effect Hook (@g12i) #50 
  * [x] Rules of Hooks (@g12i) #54 
  * [x] Building Your Own Hooks (@g12i) #60 
  * [x] Hooks API Reference (@g12i) #65 
  * [x] Hooks FAQ (@bartlomiejzuber, @jakubdrozdek) #191

### Testing

* [x] Testing Overview (@jakubdrozdek) #124 
* [x] Testing Recipes (@jakubdrozdek) #125
* [x] Testing Environments (@jakubdrozdek) #126

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [x] dont-call-proptypes (@m8ms) #157 
* [x] invalid-aria-prop (@jakubdrozdek) #88
* [x] invalid-hook-call-warning (@jakubdrozdek) #96
* [x] legacy-factories (@jakubdrozdek) #89
* [x] refs-must-have-owner (@m8ms) #158 
* [x] special-props (@jakubdrozdek) #90
* [x] unknown-prop (@jakubdrozdek) #97

### Advanced Guides

* [x] Accessibility (@danzawadzki) #61
* [x] Code-Splitting (@JakeTvvv) #86
* [x] Context (@jakubdrozdek) #129 
* [x] Error Boundaries (@PanFrontend) #128 
* [x] Forwarding Refs (@m8ms) #159 
* [x] Fragments (@jakubdrozdek) #102
* [x] Higher-Order Components (@jakubdrozdek) #156 
* [x] Integrating with Other Libraries (@jakubdrozdek) #163
* [x] JSX In Depth (@PanFrontend) #181 
* [x] Optimizing Performance (@jakubdrozdek) #210 
* [ ] Portals (@polapolaczek) #215 
* [x] React Without ES6 (@jakubdrozdek) #194 
* [x] React Without JSX (@karpiuMG) #175 
* [ ] Reconciliation (@marcin-wicha)
* [ ] Refs and the DOM
* [x] Render Props (@bartlomiejzuber) #106
* [x] Static Type Checking (@jakubdrozdek) #197
* [x] Strict Mode (@bartlomiejzuber) #113
* [x] Typechecking With PropTypes (@stepek) #185 
* [x] Uncontrolled Components (@karpiuMG) #173 
* [x] Web Components (@lffabled) #137 

### FAQ

* [x] APIs and AJAX (@Iffabled) #140 
* [x] Babel, JSX, and Build Steps (@karpiuMG) #176 
* [ ] Passing Functions to Components
* [x] Component State (@jakubdrozdek) #195
* [x] Styling and CSS (@Iffabled) #139 
* [x] File Structure (@karpiuMG) #177 
* [ ] Versioning Policy
* [x] Virtual DOM and Internals (@karpiuMG) #178 

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [x] CodeEditor (@jakubdrozdek) #55
* [x] CodeExample (@jakubdrozdek) #55
* [x] ErrorDecoder (@jakubdrozdek) #55
* [x] LayoutFooter (@jakubdrozdek) #55
* [x] LayoutHeader (@jakubdrozdek) #55
* [x] MarkdownPage (@jakubdrozdek) #55

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

* [x] addons-create-fragment (@mbiesiad) #212
* [x] error-decoder (@mbiesiad) #213
* [x] 404 (@mbiesiad) #214

**Comment by jakubdrozdek** [comment]
Do we (the maintainers) need to put the name of the page we want to translate in the comments here? Or do we just add our username next to the page without asking? ;-) Just asking.

**Comment by tesseralis** [comment]
Up to you! But it might be a nice courtesy to other contributors.

**Comment by jakubdrozdek** [comment]
Okay then, I'll start off with the style guide.

**Comment by TeoTN** [comment]
Grand! I'll go for Basics first:
* Hello World
* Introducing JSX
* Rendering Elements
* Components and Props

**Comment by jakubdrozdek** [comment]
@TeoTN:
@tesseralis wrote above: "**Please take only one page at a time**". I'm actually okay with picking multiple pages at once, since there's only three of us right now and there's lots of work ahead. But I want to know for sure. That's the verdict? :-)

**Comment by TeoTN** [comment]
I took these since they're relatively short and basic - I can adjust ;)

**Comment by jakubdrozdek** [comment]
Where do you prefer to keep the glossary? Should we create an issue for it, put it into the style guide (like the Spanish team did) or create a separate file?

**Comment by TeoTN** [comment]
I'd vote for putting it into a style guide

**Comment by jakubdrozdek** [comment]
I'll take these next:
- State and Lifecycle
- Handling Events

**Comment by tesseralis** [comment]
It's up to you -- it's your project and you can change that rule if you want if you feel it's too restrictive for a small group. Even though it might be a few of you now, more people might join in later.

**Comment by tesseralis** [comment]
Though I would encourage you to submit pull requests for pages as soon as you're done with them instead of, say, doing five pages and submitting one big pull request for all of them. One thing another language maintainer pointed out is that you could make one consistent style error that isn't caught until PR, which means you'll have to go back and change all your work!

**Comment by cvqprs** [comment]
Guys @jakubdrozdek, @bartlomiejzuber, and @TeoTN I would like to help u with this translation. Where can I start? Do you have any slack etc. to communicate?

**Comment by jakubdrozdek** [comment]
[We communicate via Github Issues](https://github.com/reactjs/pl.reactjs.org/issues/3).

**Comment by iamarek** [comment]
I'd like to help. I would take care of Getting Started page, if that's fine, since I almost have it done?

**Comment by jakubdrozdek** [comment]
@TeoTN @iamarek @cvqprs @bartlomiejzuber  Since we need approval of TWO maintainers for a PR to be merged, please don't let them wait for too long unreviewed.

**Comment by bartlomiejzuber** [comment]
@jakubdrozdek @cvqprs @TeoTN @iamarek I've made discord channel for us. You can join using this link:
https://discord.gg/U9FfxK9. I think it would be easier to communicate via discord. 🤙

**Comment by jakubdrozdek** [comment]
My discord says that this link is either invalid or outdated...

**Comment by cvqprs** [comment]
The same here, if i can suggest https://rocket.chat/ - free slack alternative.

**Comment by jakubdrozdek** [comment]
@tesseralis Could you add @iamarek to the team?

**Comment by jakubdrozdek** [comment]
@iamarek @TeoTN @cvqprs Please add the PR reference to the list above, right after you create it. It will make the list consistent and up-to-date at all times, and it will be easier to track the progress or see when and how was the file translated.

**Comment by jakubdrozdek** [comment]
I have created reactjs-org-i18n community on Spectrum (https://spectrum.chat/reactjs-org-i18n). Please join if you want to discuss anything related to the docs translation process.

**Comment by bartlomiejzuber** [comment]
> My discord says that this link is either invalid or outdated...

My bad that link could expire. Please use that one: https://discord.gg/Wz4ywjw (it should not expire).

**Comment by marcinostrouch** [comment]
@tesseralis Hello. My name is Marcin. I used to be a [professional ](http://lubimyczytac.pl/ksiazka/29487/ktoredy)English-Polish translator and I am a React enthusiast. I'd be very happy to contribute to this project. Please be so kind as to add me to the group. Here's my LinkedIn [profile](https://www.linkedin.com/in/marcin-ostrouch).

**Comment by jakubdrozdek** [comment]
Cool, more experienced volunteers! Welcome aboard!
Please go to our Spectrum channel and join the discussion. Nat will probably add you some time later.

**Comment by tesseralis** [comment]
@marcinostrouch you can start by choosing a page to translate! If you want to be a maintainer, update the [list of Polish translation maintainers](https://github.com/reactjs/reactjs.org-translation/blob/master/langs/pl.json) and get one of the current maintainers to approve it, and I'll add you to the list.

**Comment by marcinostrouch** [comment]
Great! Thank you guys @tesseralis @jakubdrozdek

**Comment by jakubdrozdek** [comment]
@iamarek @cvqprs Please do the same with the [list of Polish translation maintainers](https://github.com/reactjs/reactjs.org-translation/blob/master/langs/pl.json) (as @tesseralis mentioned) if you want to be maintainers, too.

**Comment by jakubdrozdek** [comment]
We are switching the communication platform again... But hopefully for the last time.
Please join to the Slack workspace called `react-translations` via [this link](https://rt-slack.herokuapp.com/). If it doesn't work for you for some reason, send me your e-mail address and I'll invite you.

**Comment by bartlomiejzuber** [comment]
@jakubdrozdek Provided link doesn't work for me. But that one works fine: https://rt-slack-invite.herokuapp.com/.

**Comment by iamarek** [comment]
I'm taking Lifting State Up as a next one.

**Comment by jakubdrozdek** [comment]
I'll take 'Composition vs. Inheritance'.

**Comment by jakubdrozdek** [comment]
My previous page is ready for review. Taking 'Tutorial' next - it's gonna be a long one :-)

**Comment by iamarek** [comment]
I'll translate API Reference - React

**Comment by marcinostrouch** [comment]
I'm taking "Create a New React App"

**Comment by jakubdrozdek** [comment]
I'll take testing guides next:
* Test Utilities
* Shallow Renderer
* Test Renderer

**Comment by goto1** [comment]
Hi all, I would like to contribute as well. Is the first post in this thread showing the up-to-date list of items that are currently taken and/or available for someone to contribute? Thanks.

**Comment by bartlomiejzuber** [comment]
@goto1 Hi Tom! We would love to have you on board. ✋ If you want to be a maintainer please update that file -> https://github.com/reactjs/reactjs.org-translation/blob/master/langs/pl.json and make PR so @tesseralis could add you.

**Comment by marcinostrouch** [comment]
I'm doing _Forms_

**Comment by g12i** [comment]
Hello there! I'd like to translate Hooks part :). I've added myself in #56

**Comment by jakubdrozdek** [comment]
Okay, assigned you to the first file. Once you're done and PR is merged, you'll get the other ones :)

**Comment by jakubdrozdek** [comment]
I'll take the Home Page.

**Comment by g12i** [comment]
While waiting for review I'm starting another Hooks page
> Hooks at a Glance

**Comment by patpienkowski** [comment]
@tesseralis @jakubdrozdek @bartlomiejzuber @TeoTN @cvqprs @marcinostrouch @iamarek

Hello everyone! I am willing to contribute to assist with the completion of Polish translations. I was thinking of getting started with the warnings pages unless there's a different area you would prefer that I continue. 

Thanks, Patrick.

**Comment by jakubdrozdek** [comment]
Hey, Patrick! Please add yourself to [the reactjs.org-translations repo's contributors via PR](https://github.com/reactjs/reactjs.org-translation/pulls). Then, join us on Slack. Once you're done with it, take one page from the list and translate it.
As you can see in the first post, we should focus on the Core Pages first, because they are required for the official release. But of course you can take one from the 'Others' category - as a warm-up :-)

**Comment by patpienkowski** [comment]
@jakubdrozdek Thank you I am good to go. I will start with the ReactDOM page.

**Comment by czechowiczmateusz** [comment]
Hello! I'd like to help you with Polish translations. I've added myself to maintainers in [reactjs/reactjs.org-translation#71](https://github.com/reactjs/reactjs.org-translation/pull/71). I will start with the DOM Elements part.

**Comment by patpienkowski** [comment]
ReactDom page is awaiting review. I will begin working on the ReactDomServer page next.

**Comment by jakubdrozdek** [comment]
Looks like some of the PRs wait for the author's response for too long, blocking the overall progress. Since all PRs are created from forks, we can't add our own commits to them. Let's make a rule that if a PR's author doesn't respond within 7 days, we take it over. Someone can create their own PR with translated content, apply any suggestions added to the old PR, and submit.

**Comment by czechowiczmateusz** [comment]
I've made a pull request for a DOM Elements page. I'll take ReactDOMServer next

**Comment by g12i** [comment]
I am taking _Using the State Hook_

**Comment by arekmaz** [comment]
Hi, I'd like to help too. I'll take Rendering Elements from Basics.

**Comment by arekmaz** [comment]
Next I would like to take 'Components and Props'.

**Comment by arekmaz** [comment]
'Components and Props' is waiting for review, so next I will take 'React.Component'.

**Comment by jakubdrozdek** [comment]
Taking 'React.Component'.

**Comment by jakubdrozdek** [comment]
Taking 'SyntheticEvent'.

**Comment by jakubdrozdek** [comment]
I unassigned bartlomiejzuber from two pages because of lack of presence for quite some time. They are free to be taken.

**Comment by bartlomiejzuber** [comment]
Just longer "vacation" but I am getting back on weekend. :) Currently in travel. If those will be still free till weekend I will book them again and translate them on weekend.

**Comment by jakubdrozdek** [comment]
Cool. Glad to have you back :) We just don't want to wait forever for translations, that's all. No hard feelings ;)

**Comment by jakubdrozdek** [comment]
Taking 'Conditional Rendering'

**Comment by marcinostrouch** [comment]
Doing "Conditional Rendering"

**Comment by PanFrontend** [comment]
Hi, I want to help with translations so I'll take "Error Boundaries"

**Comment by tesseralis** [comment]
I'm going to put the testing section under "Next Steps" for now so you all don't end up losing progress on Core ;)

**Comment by jakubdrozdek** [comment]
Thanks, @tesseralis! :) Make sense. Did you notice a drop in the percentage of our progress?

**Comment by jakubdrozdek** [comment]
@tesseralis Hey, Nat. Could you add @m8ms to React Community? I'd like to add him to the translation team, but I'm allowed to add Community members only.

**Comment by PanFrontend** [comment]
Hey again, I would like to help with translating 'JSX In Depth' page :)

**Comment by karpiuMG** [comment]
Hey guys, I will take "Uncontrolled Components" section :)

**Comment by karpiuMG** [comment]
I'll take "React Without JSX" next

**Comment by karpiuMG** [comment]
I'll take "Babel, JSX, and Build Steps"

**Comment by karpiuMG** [comment]
I'll take "File Structure" next

**Comment by karpiuMG** [comment]
I'll take "Virtual DOM and Internals"

**Comment by jakubdrozdek** [comment]
> ## Maintainer List
> * @jakubdrozdek
> * @bartlomiejzuber
> * @TeoTN
> * @cvqprs
> * @marcinostrouch
> * @iamarek
> * @arekmaz
> * @g12i
> 
> ## For New Translators
> To translate a page:
> 
> 1. Check that no one else has claimed your page in the checklist and comments below.
> 2. Comment below with the name of the page you would like to translate. **Please take only one page at a time**.
> 3. Clone this repo, translate your page, and submit a pull request!
> 
> Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.
> 
> Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.
> 
> ## For Maintainers
> When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:
> 
> * [ ]  Home Page (@tesseralis) #1
> 
> When PRs are merged, make sure to mark that page as completed!
> **Note:** We require two maintainers to approve a PR for it to be merged.
> 
> **Note:** Since most of the PRs are created from forks, we can't add our own commits to them. Let's make a rule that **if a PR's author doesn't respond within 7 days, we take the translated page over.** Another person can create their own PR with the translated content, apply any suggestions added to the old PR, and submit. To be fair, let's not remove entirely the original author from the list below - just add the new translator after comma.
> If the author leaves a message that they won't be available for a few days - that's fine, we'll wait.
> 
> ## Core Pages
> To do before releasing as an "official" translation. **Please translate these pages first.**
> 
> * [x]  Home Page (@jakubdrozdek) #27
> * [x]  Tutorial (@jakubdrozdek) #12
> 
> ### Basics
> * [x]  Hello World (@cvqprs @TeoTN) #38
> * [x]  Introducing JSX (@cvqprs @TeoTN) #39
> * [x]  Rendering Elements (@arekmaz) #42
> * [x]  Components and Props (@arekmaz) #45
> * [x]  State and Lifecycle (@jakubdrozdek) #8
> * [x]  Handling Events (@jakubdrozdek) #5
> * [x]  Conditional Rendering (@marcinostrouch) #59
> * [x]  Lists and Keys (@bartlomiejzuber) #58
> * [x]  Forms (@marcinostrouch ) #57
> * [x]  Lifting State Up (@iamarek) #11
> * [x]  Composition vs Inheritance (@jakubdrozdek) #10
> * [x]  Thinking in React (@marcinostrouch) #15
> 
> ### API Reference
> * [x]  React ( @cvqprs @iamarek) #48
> * [x]  React.Component (@arekmaz) #71
> * [x]  ReactDOM (@patpienkowski) #35
> * [x]  ReactDOMServer (@g12i) #81
> * [x]  DOM Elements (@cvqprs @czechowiczmateusz) #62
> * [x]  SyntheticEvent (@jakubdrozdek) #51
> * [x]  Test Utilities (@jakubdrozdek) #21
> * [x]  Shallow Renderer (@jakubdrozdek) #24
> * [x]  Test Renderer (@jakubdrozdek) #25
> * [x]  JS Environment Requirements (@cvqprs) #34
> * [x]  Glossary (@jakubdrozdek) #76
> 
> ### Navigation
> These are the navigation links that appears in the sidebar. Possibly wait until
> the corresponding sections are translated to do these.
> 
> * [x]  tutorial/nav.yml (@jakubdrozdek) #56
> * [x]  docs/nav.yml (@cvqprs) #77
> 
> ## Next Steps
> These are the next most important translations, ordered by importance:
> 
> ### Installation
> * [x]  Getting Started (@iamarek) #6
> * [x]  Add React to a Website (@cvqprs) #17
> * [x]  Create a New React App (@marcinostrouch) #23
> * [x]  CDN Links (@cvqprs) #18
> 
> ### Hooks
> Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.
> 
> * [x]  Introducing Hooks (@g12i) #28
> * [x]  Hooks at a Glance (@g12i) #33
> * [x]  Using the State Hook (@g12i) #40
> * [x]  Using the Effect Hook (@g12i) #50
> * [x]  Rules of Hooks (@g12i) #54
> * [x]  Building Your Own Hooks (@g12i) #60
> * [x]  Hooks API Reference (@g12i) #65
> * [ ]  Hooks FAQ (@bartlomiejzuber) #116
> 
> ### Testing
> * [x]  Testing Overview (@jakubdrozdek) #124
> * [x]  Testing Recipes (@jakubdrozdek) #125
> * [x]  Testing Environments (@jakubdrozdek) #126
> 
> ### Warnings
> These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
> 
> * [x]  dont-call-proptypes (@m8ms) #157
> * [x]  invalid-aria-prop (@jakubdrozdek) #88
> * [x]  invalid-hook-call-warning (@jakubdrozdek) #96
> * [x]  legacy-factories (@jakubdrozdek) #89
> * [x]  refs-must-have-owner (@m8ms) #158
> * [x]  special-props (@jakubdrozdek) #90
> * [x]  unknown-prop (@jakubdrozdek) #97
> 
> ### Advanced Guides
> * [x]  Accessibility (@danzawadzki) #61
> * [x]  Code-Splitting (@JakeTvvv) #86
> * [x]  Context (@jakubdrozdek) #129
> * [x]  Error Boundaries (@PanFrontend) #128
> * [ ]  Forwarding Refs (@m8ms) #159
> * [x]  Fragments (@jakubdrozdek) #102
> * [x]  Higher-Order Components (@jakubdrozdek) #156
> * [x]  Integrating with Other Libraries (@jakubdrozdek) #163
> * [ ]  JSX In Depth (@PanFrontend)
> * [ ]  Optimizing Performance
> * [ ]  Portals
> * [ ]  React Without ES6
> * [ ]  React Without JSX (@karpiuMG) #175
> * [ ]  Reconciliation
> * [ ]  Refs and the DOM
> * [x]  Render Props (@bartlomiejzuber) #106
> * [ ]  Static Type Checking
> * [x]  Strict Mode (@bartlomiejzuber) #113
> * [ ]  Typechecking With PropTypes
> * [x]  Uncontrolled Components (@karpiuMG) #173
> * [x]  Web Components (@lffabled) #137
> 
> ### FAQ
> * [x]  APIs and AJAX (@Iffabled) #140
> * [x]  Babel, JSX, and Build Steps (@karpiuMG) #176
> * [ ]  Passing Functions to Components
> * [ ]  Component State
> * [x]  Styling and CSS (@Iffabled) #139
> * [x]  File Structure (@karpiuMG) #177
> * [ ]  Versioning Policy
> * [ ]  Virtual DOM and Internals
> 
> ### Contributing
> Priority: Low
> 
> * [ ]  How to Contribute
> * [ ]  Codebase Overview
> * [ ]  Implementation Notes
> * [ ]  Design Principles
> 
> ### Components
> Components in `src/components` that have some text in them.
> 
> * [x]  CodeEditor (@jakubdrozdek) #55
> * [x]  CodeExample (@jakubdrozdek) #55
> * [x]  ErrorDecoder (@jakubdrozdek) #55
> * [x]  LayoutFooter (@jakubdrozdek) #55
> * [x]  LayoutHeader (@jakubdrozdek) #55
> * [x]  MarkdownPage (@jakubdrozdek) #55
> 
> ## Additional Translations
> These are not the primary translation targets.
> 
> * [ ]  Blog
> * [ ]  Community

**Comment by karpiuMG** [comment]
Taking "Passing Functions to Components"

**Comment by PanFrontend** [comment]
I'll take `Optimizing Performance` next :) JSX in depth in code review already

**Comment by karpiuMG** [comment]
Taking "Passing Functions to Components"

**Comment by stepek** [comment]
i'll take `Typechecking With PropTypes`

**Comment by jakubdrozdek** [comment]
@tesseralis Hey! I just noticed there are a couple of checkboxes missing on the translation list in the first post. Do you have the complete list and could you paste it here? Or at least tell me where can I get the latest pages list :-) Thanks in advance.

**Comment by polapolaczek** [comment]
Hey! If I may - I started translation of `Portals` page [#215 ](https://github.com/reactjs/pl.reactjs.org/pull/215)

**Comment by jakubdrozdek** [comment]
@polapolaczek @mbiesiad Please join our Slack workspace to see the glossary and check how we translate things here :-)

**Comment by mbiesiad** [comment]
@jakubdrozdek  Is this still active? Is this link correct? I'm a member of several workspaces there, but here is a problem with log in.. I'll try again close to the Fri. Let's keep in touch, greetings.

**Comment by jakubdrozdek** [comment]
It is. Maybe you need some kind of invite? I remember there's this link: https://rt-slack-invite.herokuapp.com/. Maybe it still works?

**Comment by mbiesiad** [comment]
it works! thanks a lot 🦄

**Comment by mbiesiad** [comment]
That's created as an issue. Time for little update I think. So, please add:
:white_check_mark: addons-create-fragment (@mbiesiad) #212 
:white_check_mark: error-decoder (@mbiesiad) #213  
:white_check_mark: 404 (@mbiesiad) #214

All of, merged. Thanks! 🦄 

Best wishes,

**Comment by marcin-wicha** [comment]
Hi. I'd like to translate `Reconciliation` page. To me it's a very important part of the docs that's often misunderstood.

**Comment by marcin-wicha** [comment]
@jakubdrozdek #236 Reconciliation is waiting for  review 👍

**Comment by JakubDrozd** [comment]
HI, I would like to translate: Versioning Policy

**Comment by gaearon** [comment]
Thanks to everyone who contributed to the old website translation!
Closing this issue in favor of the new translation: https://github.com/reactjs/pl.react.dev/issues/287.
